### ISSUE TITLE
`rockchip-android-10` branch: repo sync fails on `vendor/rockchip/common`

### ISSUE THREAD

**Issue by mburr-precor** [radxa/manifests#7]
Following the instructions in `README.md` for getting the rockchip-android-10 branch source code:

The `repo init` works

```
repo init -u https://github.com/radxa/manifests.git -b rockchip-android-10 -m rockchip-q-release.xml
```

but the `repo sync` command fails

```
repo sync -d --no-tags -j4
```

The following error is displayed:

```
error: Cannot fetch rk/platform/vendor/rockchip/common (GitError: rk/platform/vendor/rockchip/common update-ref: fatal: a6b6c3558f8bafbdd5d5efe3aabdcd9dbce93fe2^0: not a valid SHA1
)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/subcmds/sync.py", line 286, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/subcmds/sync.py", line 332, in _FetchHelper
    clone_filter=clone_filter)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/project.py", line 1148, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/project.py", line 2555, in _InitMRef
    self._InitAnyMRef(base + self.manifest.branch, active_git)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/project.py", line 2567, in _InitAnyMRef
    active_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/project.py", line 2968, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/mburr/devtrees/radxa/rock-pi-4c/rockchip-android-10/.repo/repo/project.py", line 3034, in runner
    (self._project.name, name, p.stderr))
error.GitError: rk/platform/vendor/rockchip/common update-ref: fatal: a6b6c3558f8bafbdd5d5efe3aabdcd9dbce93fe2^0: not a valid SHA1
```

 The missing SHA reference (`a6b6c3558f`) was committed to the `Android10_common.xml` file in:

```
in repository: ./.repo/manifests
in branches:  default
============
commit 8d1ba02
Author:     ahren <lili@vamrs.com>
AuthorDate: Tue Jan 5 11:16:33 2021 +0800
Commit:     Shine <shine@vamrs.com>
CommitDate: Tue Jan 5 16:52:46 2021 +0800

    fix Bug of USB Camera, error: Mpp reset.
    
    Signed-off-by: ahren <lili@vamrs.com>
    Change-Id: I078ea1054a029830b0bf17cb5e5c59b50fc5baa5

M       Android10_Custom.xml
============
```

Maybe someone needs to push commits to https://gitlab.com/rk-vendor/rk/platform/vendor/rockchip/common ?

**Comment by mburr-precor** [comment]
This is a dupe of https://github.com/radxa/manifests/issues/6
